### ISSUE TITLE
Add proper path to pandoc filters

### ISSUE THREAD

**Issue by sch00lb0y** [fossasia/yaydoc#70] opened 2017-06-02 12:30 UTC
### This is a
- [x] Bug report
- [ ] Feature request

### Current behaviour
path for pandoc filter are not set properly so documentation is not generating 

### Expected behaviour

documentation should generate

### Steps to reproduce
1. change filters path

**Comment by pri22296** [comment] 2017-06-03 05:59
This issue is a duplicate of #66

**Closed** 2017-06-03 13:32 UTC
