### ISSUE TITLE
Side by side images in markdowns

### ISSUE THREAD

**Issue by imujjwal96** [fossasia/yaydoc#278] opened 2017-07-18 11:13 UTC
### This is a
- [x] Bug report
- [ ] Feature request

### Description
One of the popular method for adding side by side images in Github markdown is to use HTML. Unfortunately, these images are not rendered in the generated static websites. 
http://yaydoc.herokuapp.com/preview/ujjwalb1996@gmail.com/d7a044d8-d5c8-422d-af71-8e6465f62a8f_preview/

![image](https://user-images.githubusercontent.com/8245662/28314398-1020296a-6bd8-11e7-9c9e-d51f6d04981a.png)
![image](https://user-images.githubusercontent.com/8245662/28314425-25c10230-6bd8-11e7-8d04-d52bbe36d77a.png)

**Comment by imujjwal96** [comment] 2017-07-18 11:13
@pri22296 @sch00lb0y  Any solution for this?

**Comment by sch00lb0y** [comment] 2017-07-18 11:20
Actually, we converting markdown to rst with the help of pandoc. I think the problem with pandoc. what we can do this for this exceptional case. the user has to write rst(writing our own parser won't be feasible). please check this thread for side by side image https://stackoverflow.com/questions/10219634/image-grid-in-restructuredtext-sphinx

**Comment by pri22296** [comment] 2017-07-18 11:46
I think this can be fixed by just modifying the README just a little bit.

You can see the example [here](http://pandoc.org/try/?text=%23+Screenshot%0A%0A%3Ctable%3E%0A+%3Ctr%3E%0A++%3Ctd%3E%3Cimg+src%3D%22%2Fdocs%2Fscreenshots%2Fscreenshot_1.png%22%3E%3C%2Ftd%3E%0A++%3Ctd%3E%3Cimg+src%3D%22%2Fdocs%2Fscreenshots%2Fscreenshot_3.png%22%3E%3C%2Ftd%3E%0A++%3Ctd%3E%3Cimg+src%3D%22%2Fdocs%2Fscreenshots%2Fscreenshot_5.png%22%3E%3C%2Ftd%3E%0A++%3Ctd%3E%3Cimg+src%3D%22%2Fdocs%2Fscreenshots%2Fscreenshot_2.png%22%3E%3C%2Ftd%3E%0A++%3Ctd%3E%3Cimg+src%3D%22%2Fdocs%2Fscreenshots%2Fscreenshot_4.png%22%3E%3C%2Ftd%3E%0A+%3C%2Ftr%3E%0A%3C%2Ftable%3E&from=markdown_github&to=rst)

**Comment by imujjwal96** [comment] 2017-07-18 12:04
No its not! Let me fix it and deploy again!

**Comment by imujjwal96** [comment] 2017-07-18 14:15
http://yaydoc.herokuapp.com/preview/ujjwalb1996@gmail.com/9040e134-ec97-4815-8332-934f01937a09_preview/
Didn't work

**Comment by pri22296** [comment] 2017-07-18 17:46
Although, I did make this work by removing the indentation from the html, There are two reasons this will still not work.

- While including documents, we modify any links we encounter, to account for the relative paths. i.e README refers to an image like `docs/images/image_1.png` but when included from index, the path should be `images/image_1.png`. But we only modify links in markdown format(`[title](link)`) and rst format(```title <link>_```). The links in an embedded html aren't modified
- Sphinx also doesn't detect those images and hence doesn't copy them to `_static`

@imujjwal96 @sch00lb0y What do you suggest

**Comment by imujjwal96** [comment] 2017-07-18 18:57
The indentation will have to be fixed manually from user's end. We shouldn't do anything about it. 
The concern for rendering images has been there. When the docpath is `docs/` the top image is not generated: http://yaydoc.herokuapp.com/preview/ujjwalb1996@gmail.com/cc38484b-5287-4361-81a2-70de21da291a_preview/
Whereas, when the docpath is `.` the docs are http://yaydoc.herokuapp.com/preview/ujjwalb1996@gmail.com/4edc20d1-1edc-4028-8159-a8d25729a6d5_preview/

**Comment by imujjwal96** [comment] 2017-07-18 19:36
@pri22296 Can you do it with embedded HTML' src link?

**Comment by imujjwal96** [comment] 2017-07-18 20:08
Will something like this work? 
![image](https://user-images.githubusercontent.com/8245662/28337318-e3cb4426-6c22-11e7-8bbe-f278ef2054de.png)

**Comment by pri22296** [comment] 2017-07-19 07:43
I guess yeah. Will also need to figure out a way to inc;lude those imags in the build

**Comment by pri22296** [comment] 2017-07-19 16:34
I tried using a HTMLParser here instead of regex. The approach is more flexible and much more readable and It does work very well. The only downside is that if the file contains text in the form of `<tag>`, closing tags are also created. @imujjwal96 Please give your suggestion as to how to handle this or should I fallback to using regex.

**Comment by imujjwal96** [comment] 2017-07-19 16:47
Can you please explain why the closing tag is created?
Image tag don't really need a closing tag, as <img /> works same as <img></img>

**Comment by pri22296** [comment] 2017-07-19 16:56
No, the `img` tag is fine. What I'm actually doing is passing the entire document through a HTMLParser, and using it to access <img> and <a> tags. Now since the document would be a mix of html and normal text, It may contain lines like these.

`git clone -b <branch> <remote_repo>`

The problem is though that now the parser adds the closing tags
</branch> and  </remote_repo> at the end.

**Comment by imujjwal96** [comment] 2017-07-19 17:07
Isn't there an option to specify valid tags?

**Comment by pri22296** [comment] 2017-07-19 17:32
I don't think so.

**Comment by imujjwal96** [comment] 2017-07-19 17:50
What other options do we have?

**Comment by pri22296** [comment] 2017-07-19 17:52
I could try to compare the original document and the new documents and try to strip the extra created closing tags.

**Comment by imujjwal96** [comment] 2017-07-19 17:52
<here> `<here>`

**Comment by pri22296** [comment] 2017-07-19 18:00
I am not able to follow. Can you explain in more detail?

**Comment by imujjwal96** [comment] 2017-07-19 18:09
Will it be possible to prevent the `code block` from being parsed? That is the only place where a user would provide the `<angular brackets>`

**Comment by pri22296** [comment] 2017-07-19 19:01
I would be possible with some regex based hacks which would remove the advantage of using the advantage of a html parser in the first place. Also the regex would be complex as we would need to handle both inline and block level code blocks for both markdown and ReST. falling back to a regex based solution for now.

**Comment by pri22296** [comment] 2017-07-19 19:35
![screenshot 186](https://user-images.githubusercontent.com/11555869/28385817-1785aa26-6ce7-11e7-92dc-8fd682507d53.png)

The solution works well. You can also see that the links have been modified according to the path.
One final challenge remains though is how to include the images in the build.
If it had been a markdown link, sphinx would have generated the appropriate link like `_static/...`.
What should be done here. Should we try to emulate what sphinx does in this case? @imujjwal96 @sch00lb0y Please give your suggestions.

**Comment by pri22296** [comment] 2017-07-20 08:36
Upon some research, I found out that one easy way out of this situation would be to introduce a constraint that images referred using this method should be in a `_static` directory inside docpath. Sphinx would then copy those images to `_build/html/_static`. Hence the same link would work both on GitHub and generated docs

**Comment by imujjwal96** [comment] 2017-07-20 08:39
I was thinking the same. But, can this constraint be justified?
Anyway, i think we should resort with your solution for the time being.

**Closed** 2017-07-20 13:50 UTC
Labels: has-PR
